import puppeteer from 'puppeteer';

(async () => {
  let browser;
  try {
    console.log('Launching browser...');
    browser = await puppeteer.launch();
    const page = await browser.newPage();
    
    console.log('Navigating to http://localhost:3000...');
    await page.goto('http://localhost:3000', { waitUntil: 'networkidle0' });
    
    console.log('Scrolling down to reveal the floating navbar...');
    await page.evaluate(() => {
      window.scrollBy(0, window.innerHeight);
    });
    
    // Wait a bit for the animation
    await new Promise(r => setTimeout(r, 1000));
    
    console.log('Waiting for Apply button...');
    await page.waitForSelector('.nav-cta-btn.nav-cta-btn-dock', { visible: true });
    
    console.log('Clicking Apply button...');
    await page.click('.nav-cta-btn.nav-cta-btn-dock');
    
    console.log('Waiting for modal to appear...');
    await page.waitForSelector('.modal-overlay', { visible: true });
    
    console.log('Modal is open! Filling out the form...');
    
    // Fill the form fields
    await page.type('#fullName', 'Test User');
    await page.type('#email', 'test@axventures.com');
    await page.type('#companyName', 'Test Company');
    await page.type('#pitch', 'This is a test pitch generated by Puppeteer.');
    
    // Select stage (optional, default is idea)
    await page.select('#stage', 'mvp');
    
    console.log('Form filled. You can uncomment the submission part if you want to test submit.');
    
    // Uncomment below to actually submit and test the success message
    // console.log('Submitting form...');
    // await page.click('button[type="submit"]');
    // await page.waitForSelector('.animate-slide-up', { visible: true, timeout: 5000 });
    // console.log('Success message appeared!');
    
    // Take a screenshot
    await page.screenshot({ path: 'modal_test_screenshot.png' });
    console.log('Screenshot saved to modal_test_screenshot.png');
    
  } catch(e) {
    console.error('An error occurred during the Puppeteer test:', e);
  } finally {
    if (browser) {
      console.log('Closing browser...');
      await browser.close();
    }
  }
})();
